name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Test Workflow"]
    types: [completed]
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !contains(github.event.workflow_run.head_commit.message, 'ci:false')
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf project || true
            mkdir project && cd project
            echo "Fetching repository..."
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .
            git checkout ${{ github.ref }}
            
            echo "Building project..."
            mvn clean package -DskipTests
            
            echo "dockering..."
            docker stop listopia-app || true
            docker rm listopia-app || true
            docker rmi listopia-app || true
            docker build -f deploy/Dockerfile -t listopia-app . || true
            docker run -d \
              --name listopia-app \
              -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e MJ_APIKEY_PUBLIC="${{ secrets.MJ_APIKEY_PUBLIC }}" \
              -e MJ_APIKEY_PRIVATE="${{ secrets.MJ_APIKEY_PRIVATE }}" \
              -e RECAPTCHA_SECRET="${{ secrets.RECAPTCHA_SECRET }}" \
              -e TMDB_APIKEY="${{ secrets.TMDB_APIKEY }}" \
              listopia-app
